In [25]:
import numpy as np

In [21]:
#Exercise 1: Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1
matrix=a1.reshape(2,5)
print(matrix)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
#Exercise 2:Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

array1=np.arange(1,21)
array1



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
print(array1[5:16])

[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#Exercise 3: Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [33]:
import pandas as pd

In [41]:
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series

apples     3
bananas    2
oranges    1
dtype: int64

In [43]:
series['pears'] = 4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [ ]:
#Exercise 4:Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [45]:

data1 = {'name': ['Archana', 'Anayra', 'Roshan', 'Anuraj', 'Thara', 'Naveen', 'Greeshma', 'Abirami', 'Vishnu', 'Sanjay'],
    'age': [26, 2, 22, 35, 48, 40, 23, 29, 31, 27],
    'gender': ['Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']}
df = pd.DataFrame(data1)
print(df)


       name  age  gender
0   Archana   26  Female
1    Anayra    2  Female
2    Roshan   22    Male
3    Anuraj   35    Male
4     Thara   48  Female
5    Naveen   40    Male
6  Greeshma   23  Female
7   Abirami   29  Female
8    Vishnu   31    Male
9    Sanjay   27    Male


In [ ]:
#Exercise 5:Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [47]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations

print(df)

       name  age  gender  occupation
0   Archana   26  Female  Programmer
1    Anayra    2  Female     Manager
2    Roshan   22    Male     Analyst
3    Anuraj   35    Male  Programmer
4     Thara   48  Female     Manager
5    Naveen   40    Male     Analyst
6  Greeshma   23  Female  Programmer
7   Abirami   29  Female     Manager
8    Vishnu   31    Male     Analyst
9    Sanjay   27    Male  Programmer


In [ ]:
Exercise 6: Select the rows of the dataframe where the age is greater than or equal to 30

In [49]:
selected_rows = df[df['age'] >= 30]
print(selected_rows)

     name  age  gender  occupation
3  Anuraj   35    Male  Programmer
4   Thara   48  Female     Manager
5  Naveen   40    Male     Analyst
8  Vishnu   31    Male     Analyst


In [ ]:
 Exercise 7:  Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [57]:
df.to_csv('data1.csv', index=False)

df_from_csv = pd.read_csv('data1.csv')
print(df_from_csv)

       name  age  gender  occupation
0   Archana   26  Female  Programmer
1    Anayra    2  Female     Manager
2    Roshan   22    Male     Analyst
3    Anuraj   35    Male  Programmer
4     Thara   48  Female     Manager
5    Naveen   40    Male     Analyst
6  Greeshma   23  Female  Programmer
7   Abirami   29  Female     Manager
8    Vishnu   31    Male     Analyst
9    Sanjay   27    Male  Programmer
